#!/usr/bin/env bash
#  ____ _____ 
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |  	http://www.youtube.com/c/DistroTube
# | |_| || |  	http://www.gitlab.com/dwt1/ 
# |____/ |_|  	
#        
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm


### AUTOSTART ####
setxkbmap de neo -option 
xsetroot -cursor_name left_ptr &
sxhkd -m -1 &
xrandr --output HDMI-0 --off --output DP-0 --off --output DP-1 --mode 1920x1080 --pos 3000x0 --rotate normal --output DP-2 --off --output DP-3 --primary --mode 1920x1080 --pos 1080x0 --rotate normal --output DP-4 --off --output DP-5 --mode 1920x1080 --pos 0x0 --rotate left
picom &
$HOME/.config/polybar/bspwm.sh &
protonmail-bridge &
nitrogen --restore &
playerctl &
dunst &
killall flameshot && flameshot &
nm-applet &
blueman-applet &
pasystray & 
nextcloud &
clipmenud &

### Select only ONE of the following four ways to set the wallpaper.
# xargs xwallpaper --stretch < ~/.cache/wall &
# ~/.fehbg &
# feh --randomize --bg-fill /usr/share/backgrounds/dtos-backgrounds/* &
# nitrogen --restore &

#### MONITORS ####
for monitor in $(bspc query -M)
do
    # set the workspaces on each monitor to 1-9
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9
done
   #polybar hidden when fullscreen for vlc, youtube, mpv ...
#    xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
#pc 
#bspc wm -O DP-3 DP-1
#bspc monitor DP-3 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 0

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    10
bspc config top_padding                   50
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color	              "#3c3836"
bspc config active_border_color		      "#1e1e1e"
bspc config focused_border_color	      "#ebdbb2"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



